import './globals.css'
import { Ubuntu } from 'next/font/google'

//component
import Navbar from './component/Navbar'

const ubuntu = Ubuntu({ subsets: ['latin'], weight:'400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Navbar/>
        {children}
        
      </body>
    </html>
  )
}
